--- 
- 'array.c'
- 'io.c'
- 'st.c'
- 'lex.c'
- 'util.c'
- 'process.c'
- 're.c'
- 'time.c'
- 'compar.c'
- 'random.c'
- 'bignum.c'
- 'dir.c'
- 'prec.c'
- 'struct.c'
- 'math.c'
- 'range.c'
- 'file.c'
- 'numeric.c'
- 'signal.c'