--- 
- 'array.c'
- 'io.c'
- 'st.c'
- 'lex.c'
- 'util.c'
- 'process.c'
- 're.c'
- 'time.c'
- 'compar.c'
- 'random.c'
- 'bignum.c'
- 'dir.c'
- 'prec.c'
- 'struct.c'
- 'math.c'
- 'range.c'
- 'file.c'
- 'numeric.c'
- 'signal.c'
- 'sprintf.c'
- 'time.c'
- 'regex.c'
- 'marshal.c'
- 'dln.c'
- 'hash.c'
- 'string.c'
- 'pack.c'
- 'error.c'
- 'object.c'
- 'parse.y'
- 'inits.c'
- 'main.c'
#- 'ruby.c'
#- 'enum.c'
#- 'class.c'
#- 'eval.c' 
#- 'gc.c'