---
- rb_class_of
- rb_type
- rb_special_const_p
- memfill
- rb_ary_modify_check
- rb_ary_elt
- bigfixize
- bracket
- do_stat
- do_opendir
- has_magic
- find_dirsep
- remove_backslashes
- glob_make_pattern
- rb_glob2
- err_print
- init_funcname_len
- objcdummyfunction
- init_syntax_once
- print_mbc
- print_partial_compiled_pattern
- print_compiled_pattern
- calculate_must_string
- read_backslash
- insert_jump_n
- insert_op
- slow_match
- slow_search
- bm_init_skip
- bm_search
- init_regs
- re_match_exec
- memcmp_translate